//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PRESENTACION.wsColegio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsColegioSoap", Namespace="http://tempuri.org/")]
    public partial class wsColegio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarEstudianteNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarApoderadoNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarCursoPorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarInscripcionPorNombreEstudianteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsColegio() {
            this.Url = global::PRESENTACION.Properties.Settings.Default.PRESENTACION_wsColegio_wsColegio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarEstudianteNombreCompletedEventHandler buscarEstudianteNombreCompleted;
        
        /// <remarks/>
        public event buscarApoderadoNombreCompletedEventHandler buscarApoderadoNombreCompleted;
        
        /// <remarks/>
        public event buscarCursoPorNombreCompletedEventHandler buscarCursoPorNombreCompleted;
        
        /// <remarks/>
        public event buscarInscripcionPorNombreEstudianteCompletedEventHandler buscarInscripcionPorNombreEstudianteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarEstudianteNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarEstudianteNombre(string nombre) {
            object[] results = this.Invoke("buscarEstudianteNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarEstudianteNombreAsync(string nombre) {
            this.buscarEstudianteNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarEstudianteNombreAsync(string nombre, object userState) {
            if ((this.buscarEstudianteNombreOperationCompleted == null)) {
                this.buscarEstudianteNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarEstudianteNombreOperationCompleted);
            }
            this.InvokeAsync("buscarEstudianteNombre", new object[] {
                        nombre}, this.buscarEstudianteNombreOperationCompleted, userState);
        }
        
        private void OnbuscarEstudianteNombreOperationCompleted(object arg) {
            if ((this.buscarEstudianteNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarEstudianteNombreCompleted(this, new buscarEstudianteNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarApoderadoNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarApoderadoNombre(string nombre) {
            object[] results = this.Invoke("buscarApoderadoNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarApoderadoNombreAsync(string nombre) {
            this.buscarApoderadoNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarApoderadoNombreAsync(string nombre, object userState) {
            if ((this.buscarApoderadoNombreOperationCompleted == null)) {
                this.buscarApoderadoNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarApoderadoNombreOperationCompleted);
            }
            this.InvokeAsync("buscarApoderadoNombre", new object[] {
                        nombre}, this.buscarApoderadoNombreOperationCompleted, userState);
        }
        
        private void OnbuscarApoderadoNombreOperationCompleted(object arg) {
            if ((this.buscarApoderadoNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarApoderadoNombreCompleted(this, new buscarApoderadoNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarCursoPorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarCursoPorNombre(string nombre) {
            object[] results = this.Invoke("buscarCursoPorNombre", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarCursoPorNombreAsync(string nombre) {
            this.buscarCursoPorNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarCursoPorNombreAsync(string nombre, object userState) {
            if ((this.buscarCursoPorNombreOperationCompleted == null)) {
                this.buscarCursoPorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarCursoPorNombreOperationCompleted);
            }
            this.InvokeAsync("buscarCursoPorNombre", new object[] {
                        nombre}, this.buscarCursoPorNombreOperationCompleted, userState);
        }
        
        private void OnbuscarCursoPorNombreOperationCompleted(object arg) {
            if ((this.buscarCursoPorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarCursoPorNombreCompleted(this, new buscarCursoPorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarInscripcionPorNombreEstudiante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarInscripcionPorNombreEstudiante(string nombre) {
            object[] results = this.Invoke("buscarInscripcionPorNombreEstudiante", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarInscripcionPorNombreEstudianteAsync(string nombre) {
            this.buscarInscripcionPorNombreEstudianteAsync(nombre, null);
        }
        
        /// <remarks/>
        public void buscarInscripcionPorNombreEstudianteAsync(string nombre, object userState) {
            if ((this.buscarInscripcionPorNombreEstudianteOperationCompleted == null)) {
                this.buscarInscripcionPorNombreEstudianteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarInscripcionPorNombreEstudianteOperationCompleted);
            }
            this.InvokeAsync("buscarInscripcionPorNombreEstudiante", new object[] {
                        nombre}, this.buscarInscripcionPorNombreEstudianteOperationCompleted, userState);
        }
        
        private void OnbuscarInscripcionPorNombreEstudianteOperationCompleted(object arg) {
            if ((this.buscarInscripcionPorNombreEstudianteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarInscripcionPorNombreEstudianteCompleted(this, new buscarInscripcionPorNombreEstudianteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarEstudianteNombreCompletedEventHandler(object sender, buscarEstudianteNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarEstudianteNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarEstudianteNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarApoderadoNombreCompletedEventHandler(object sender, buscarApoderadoNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarApoderadoNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarApoderadoNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarCursoPorNombreCompletedEventHandler(object sender, buscarCursoPorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarCursoPorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarCursoPorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void buscarInscripcionPorNombreEstudianteCompletedEventHandler(object sender, buscarInscripcionPorNombreEstudianteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarInscripcionPorNombreEstudianteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarInscripcionPorNombreEstudianteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591